### ISSUE TITLE
EMQ的COAP插件相关问题

### ISSUE THREAD

**Issue by NoobSmall** [emqx/emqx-coap#148]
在链接      https://github.com/emqx/emqx-coap
页面中的     COAP客户端发布操作中的
  PUT  coap://localhost/mqtt/{topicname}?c={clientid}&u={username}&p={password}

这里的mqtt指的COAP的Uri-Port
但  topicname 和 clientid是COAP的什么选项名称呢？

**Comment by HJianBo** [comment]
The `{xx}` is a placeholder character, not an Option of CoAP. You should replace it with your really Topic Name or Client Id
