### ISSUE TITLE
COAP on IPv6

### ISSUE THREAD

**Issue by maronows** [emqx/emqx-coap#164]
Hi,

I'm trying to enable CoAP listener on IPv6 interface but can't find option for this. Putting ":::5683" in the plugin config doesn't work as it expects just integer as the port.

Is this supported? If so, what's the config for this?

**Comment by HJianBo** [comment]
@maronows Thanks for your suggestion.

 We plan to implement it in the 4.1.0

**Comment by maronows** [comment]
Any idea when will 4.1.0 be available?

**Comment by HJianBo** [comment]
The 4.1.-beta.2 will be released one month later

**Comment by maronows** [comment]
OK. Thanks for the info.

**Comment by qingchuwudi** [comment]
The [v4.1.0-alpha.3](https://github.com/emqx/emqx/releases/tag/v4.1.0-alpha.3) support IPv6 now.
